name: metro
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13.7
  - numpy=2.3.3
  - pandas=2.3.2
  - matplotlib=3.10.6
  - pillow=11.0.0
  - networkx=3.3
  - sympy=1.13.3
  - pyyaml=6.0.2
  - openpyxl=3.1.5
  - tqdm=4.67.1
  - setuptools=70.2.0
  - pip=25.2
  - pytorch
  - torchvision
  - polars=1.33.1
  - pip:
    - xmltodict==1.0.2
