# default parameters. all experimental parameters should use these unless set as otherwise in another custom config

# run parameters
run_name: 'default'

# vae parameters
d_input_tr: 1
d_input_me: 1
d_hidden: 1
d_latent: 1

# training parameters
batch_size: 1
learning_rate: 1
num_epochs: 1
beta: 1.0
lambda_me: 1.0
lambda_tr: 1.0

# data parameters
data_fp: '/home/ubuntu/tbd-project-25/data/merged_df.csv'

# device
device: 'cpu'  # 'cuda', or 'cpu'